version: "3.5"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      - PUID=1000
      - PGID=1000
      #- TZ=Asia/Seoul
      #- JELLYFIN_PublishedServerUrl=http://192.168.1.111/jellyfin/
    network_mode: 'host'
    #group_add:
    #  - "107"
    #ports:
    #  - 8096:8096
    #  - 8920:8920 #optional
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/media:/media
      - /jellyfin/cache:/cache
    #devices:    
    #  - /dev/dri/renderD128:/dev/dri/renderD128
    #  - /dev/dri/card0:/dev/dri/card0
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    restart: unless-stopped
